version: "3.8"
services:
  web:
    container_name: web-container
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    container_name: api-container
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks: 
      - network-backend
 
  db:
    container_name: db-container
    image: postgres
    restart: always
    user: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks: 
      - network-backend
    expose:
      - "5432:5432"


networks:
  network-backend: 

volumes: 
  db-data: