FROM node:16-alpine3.11

WORKDIR /usr/app

COPY . .
# COPY package*.json ./
RUN npm install

RUN mkdir -p /usr/app/src/public/pokemon/pictures

RUN npm install prisma -g
RUN npx prisma generate

COPY bash/migrate-and-start.sh .
RUN chmod +x migrate-and-start.sh

RUN npm run build

EXPOSE 8080

# CMD ["npm", "run", "dev"]
CMD ["./migrate-and-start.sh"]
ENTRYPOINT ["/bin/sh"]